name: Docker release
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: yearbook
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: set up buildx
        uses: docker/setup-buildx-action@v1
      - name: log in to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: mathisburger
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/mathisburger/yearbook:latest